# Generated by Django 5.1.6 on 2025-03-12 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organization',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Логин должен начинаться с 'S' или 'F' или 'G', за которым следует 8 цифр (например, S22016275 или F12345678).", regex='^[SFG]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('moderator', 'Moderator'), ('organization', 'Organization'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
