# Generated by Django 5.1.6 on 2025-03-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_organization_alter_user_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_path',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
