# Generated by Django 4.2.20 on 2025-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreminder',
            name='reminded',
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, '3h'), (2, '1h'), (3, '20m')], default=0),
        ),
    ]
